"""Inizializzazione del database

Revision ID: 8bd3b89b4d5c
Revises: 0dab4e492b95
Create Date: 2024-09-27 20:22:57.600829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd3b89b4d5c'
down_revision = '0dab4e492b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###
